---
- hosts: omepa
  become: yes
  tasks:
    - name: install what i need
      apt:
        name:
          - realmd
          - sssd
          - sssd-tools
          - libnss-sss
          - libpam-sss
          - adcli
          - samba-common-bin
          - oddjob
          - oddjob-mkhomedir
          - packagekit
          - krb5-user
        state: latest
        update_cache: yes
        force_apt_get: yes
